/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    application
    checkstyle
    pmd
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "ch.zhaw.it.pm1.nullpointerexception.texteditor.StartUp"
}

checkstyle {
    toolVersion = "10.12.4"
}

pmd {
    toolVersion = "6.55.0"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<Checkstyle> {
    reports {
        xml.required = true
        html.required = true
    }
}

tasks.withType<Pmd> {
    reports {
        xml.required = true
        html.required = true
    }
}
